### ISSUE TITLE
Rename accessor to adapter

### ISSUE THREAD

**Issue by JirkaChadima** [windingtree/off-chain-adapter-swarm#4]
To be consistent with the rest of the adapters and wt-js-libs new naming convention, accessors are now adapters.

See https://github.com/windingtree/off-chain-adapter-in-memory/pull/3 for an example. There's probably no need to re-encode travis env vars, although we need to re-add the repository on coveralls

**Comment by hynek-urban** [comment]
Done. (I just didn't find out how to propagate the renaming to Travis, but I suppose this isn't of such an importance.)
